listen:
  address: :9130
  metricspath: /metrics
unifi:
  address: https://my-controller.example.io
  username: your_username
  password: fakey_password
  site: Default
  insecure: false
  timeout: 5s
